[[plugin]]
id = "k4n4t4/hypr-submap"
name = "Hyprland Submap"
version = "1.0.0"
plugin_api = 5
author = "k4n4t4"
license = "MIT"
dependencies = ["socat"]
tags = ["hyprland", "bar"]
icon = "keyboard"
description = "Hyprland submap plugin for Noctalia"
